# Flood Control Project Data Breakdown

### Import Packages

In [1]:
import pandas as pd
from dateutil.relativedelta import relativedelta

### Generate DataFrames

In [2]:
df = pd.read_csv('flood_control/flood-control-projects-table_2025-09-19.csv')

# Check the dataframe
df.head(2)

,GlobalID,InfraYear,Region,Province,Municipality,ImplementingOffice,ProjectID,ProjectDescription,ProjectComponentID,ProjectComponentDescription,...,FundingYear,LegislativeDistrict,DistrictEngineeringOffice,ABC_String,ContractCost_String,CompletionDateActual,StartDate,type,slug,_geo
0,79e8be69-90ab-488d-bf10-9204d41338ab,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824759LZ,Construction of Babuyan River Flood Control St...,P00824759LZ-CW1,Construction of Flood Mitigation Structure - C...,...,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,17963475,17961569.07,2024-05-23,02/15/2024,flood_control,construction-of-babuyan-river-flood-control-st...,[object Object]
1,dea02c2f-d69d-4757-8d21-853e001736c5,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824758LZ,Construction of Flood Control Strucurue along ...,P00824758LZ-CW1,Construction of Flood Mitigation Structure - C...,...,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,17370000,17369992.99,2024-07-19,02/23/2024,flood_control,construction-of-flood-control-strucurue-along-...,[object Object]

### See Table Columns

In [3]:
# Dataframe columns
df.columns

Index(['GlobalID', 'InfraYear', 'Region', 'Province', 'Municipality',
       'ImplementingOffice', 'ProjectID', 'ProjectDescription',
       'ProjectComponentID', 'ProjectComponentDescription', 'Program',
       'TypeofWork', 'infra_type', 'Longitude', 'Latitude', 'ContractID',
       'ABC', 'ContractCost', 'CompletionDateOriginal', 'CompletionYear',
       'Contractor', 'ObjectId', 'CreationDate', 'Creator', 'EditDate',
       'Editor', 'FundingYear', 'LegislativeDistrict',
       'DistrictEngineeringOffice', 'ABC_String', 'ContractCost_String',
       'CompletionDateActual', 'StartDate', 'type', 'slug', '_geo'],
      dtype='object')

### See The Infastructure Build Per Year

In [4]:
# Checking the Infrastructure Year
df['InfraYear'].value_counts().sort_index()

InfraYear
2018       7
2019       3
2020      36
2021     620
2022    3334
2023    3466
2024    2354
2025      35
Name: count, dtype: int64

### Check Total Unique Numbers Of Contractors In Flood-Control Projects

In [5]:
df['Contractor'].nunique()

2409

In [6]:
df['Contractor'].head()

0                                AZARRAGA CONSTRUCTION
1                                AZARRAGA CONSTRUCTION
2                             F.F. GALANG CONSTRUCTION
3                       PALBIC CONSTRUCTION AND SUPPLY
4    OCTAGON CONCRETE SOLUTIONS INC. / MAC BUILDERS...
Name: Contractor, dtype: object

### Getting The Estimated Average Project Per Contractor

In [7]:
# From the website:

Total_Projects = 9855
Unique_Contractors = 344

Average_Projects_Per_Contractor = Total_Projects / Unique_Contractors

# Getting the average
Average_Projects_Per_Contractor

28.648255813953487

### Count The Total Flood-Control Projects Made

In [8]:
# Count the total flood control projects
df['type'].value_counts()

type
flood_control    9855
Name: count, dtype: int64

### Redefined the DataFrame Table

In [9]:
# Get only what needed in dataframe
df = df[['InfraYear','Region', 'Province', 'Municipality', 'ProjectDescription', 'ContractCost', 'Contractor', 'CompletionDateActual', 'CompletionDateOriginal', 'StartDate', 'ContractID']]


df.head(2)

,InfraYear,Region,Province,Municipality,ProjectDescription,ContractCost,Contractor,CompletionDateActual,CompletionDateOriginal,StartDate,ContractID
0,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Construction of Babuyan River Flood Control St...,17961569.07,AZARRAGA CONSTRUCTION,2024-05-23,1.720829e+12,02/15/2024,24EG0058
1,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Construction of Flood Control Strucurue along ...,17369992.99,AZARRAGA CONSTRUCTION,2024-07-19,1.721693e+12,02/23/2024,24EG0057

### Check The DataTypes

In [10]:
# See the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9855 entries, 0 to 9854
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   InfraYear               9855 non-null   int64
 1   Region                  9855 non-null   object
 2   Province                9855 non-null   object
 3   Municipality            9189 non-null   object
 4   ProjectDescription      9855 non-null   object
 5   ContractCost            9855 non-null   float64
 6   Contractor              9855 non-null   object
 7   CompletionDateActual    9855 non-null   object
 8   CompletionDateOriginal  9851 non-null   float64
 9   StartDate               9855 non-null   object
 10  ContractID              9855 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 847.0+ KB

### Correct Datatypes In Datetime

In [11]:
# Convert to datetime (from ms -> datetime) and format as YYYY-MM-DD
df['CompletionDate'] = pd.to_datetime(df['CompletionDateOriginal'], unit="ms", errors='coerce')

# Drop the old column
df = df.drop(columns=['CompletionDateOriginal'])

# Convert StartDate from string MM/DD/YYYY -> datetime
df['StartDate'] = df['StartDate'].astype(str).str.strip()
df['StartDate'] = pd.to_datetime(df['StartDate'], format='%m/%d/%Y', errors='coerce')

# Convert other date columns
df['CompletionDateActual'] = pd.to_datetime(df['CompletionDateActual'], errors="coerce")

# Ensure uniform datetime type (no premature string formatting)
# If you need to DISPLAY as YYYY-MM-DD, format when printing/exporting:
df['StartDate'] = df['StartDate'].dt.strftime('%Y-%m-%d')
df['CompletionDate'] = df['CompletionDate'].dt.strftime('%Y-%m-%d')
df['CompletionDateActual'] = df['CompletionDateActual'].dt.strftime('%Y-%m-%d')

# Show output
print(df.head(5))

   InfraYear       Region Province                              Municipality  \
0       2024  Region IV-B  PALAWAN  PUERTO PRINCESA CITY (CAPITAL) (PALAWAN)
1       2024  Region IV-B  PALAWAN  PUERTO PRINCESA CITY (CAPITAL) (PALAWAN)
2       2024  Region IV-B  PALAWAN  PUERTO PRINCESA CITY (CAPITAL) (PALAWAN)
3       2023  Region IV-B  PALAWAN  PUERTO PRINCESA CITY (CAPITAL) (PALAWAN)
4       2024  Region IV-B  PALAWAN  PUERTO PRINCESA CITY (CAPITAL) (PALAWAN)

                                  ProjectDescription  ContractCost  \
0  Construction of Babuyan River Flood Control St...  1.796157e+07
1  Construction of Flood Control Strucurue along ...  1.736999e+07
2  Construction of Babuyan River Flood Control St...  1.680261e+07
3  Construction of Flood Control Structure, Baran...  4.899590e+06
4  Construction of Tanabag River Waterway, (Upstr...  1.543954e+08

                                          Contractor CompletionDateActual  \
0                              AZARRAGA CONSTRUCTION           2024-05-23
1                              AZARRAGA CONSTRUCTION           2024-07-19
2                           F.F. GALANG CONSTRUCTION           2024-07-24
3                     PALBIC CONSTRUCTION AND SUPPLY           2023-05-05
4  OCTAGON CONCRETE SOLUTIONS INC. / MAC BUILDERS...           2024-09-05

    StartDate ContractID CompletionDate
0  2024-02-15   24EG0058     2024-07-13
1  2024-02-23   24EG0057     2024-07-23
2  2024-02-23   24EG0017     2024-07-24
3  2023-02-15   23EG0016     2023-04-21
4  2024-03-09   24E00127     2025-01-17

### Getting The Lowest Cost Project

In [12]:
# Getting the minimum cost project
min_cost = df['ContractCost'].min()

formatted_min = f"{min_cost:,.2f}"

print("Min ContactCost:", formatted_min)

Min ContactCost: 1,154,359.00

In [13]:
# Show the minimum cost project in table
df[(df['ContractCost'] == 1154359)]

,InfraYear,Region,Province,Municipality,ProjectDescription,ContractCost,Contractor,CompletionDateActual,StartDate,ContractID,CompletionDate
6313,2023,Region VI,NEGROS OCCIDENTAL,LA CASTELLANA (NEGROS OCCIDENTAL),Repair/Rehabilitation of Pantao Bridge Stone M...,1154359.0,"ST. RAYMUND CONSTRUCTION, INC.",2023-07-09,2023-04-12,23GL0089,2023-07-02

### Getting The Highest Cost Project

In [14]:
# Getting the highest cost project
max_cost = df['ContractCost'].max()

formatted_max = f"{max_cost:,.2f}"

print("Max ContactCost:", formatted_max)

Max ContactCost: 289,500,000.00

In [15]:
df[(df['ContractCost'] == 289500000)]

,InfraYear,Region,Province,Municipality,ProjectDescription,ContractCost,Contractor,CompletionDateActual,StartDate,ContractID,CompletionDate
160,2022,Region III,TARLAC,CAMILING (TARLAC),"Construction of Camiling-Agno River Floodway, ...",289500000.0,BMK CONSTRUCTION CORPORATION (FORMERLY B.M.K. ...,2024-02-19,2022-07-25,22C00083,2024-02-18

### Modified The Data In Millions

In [16]:
df['ContractCost'] = pd.to_numeric(df['ContractCost'], errors='coerce')

df['ContractCost'] = (df['ContractCost'] / 1000000).round(1).astype(str) + "M"

In [24]:
df['ContractCost']

0        18.0M
1        17.4M
2        16.8M
3         4.9M
4       154.4M
         ...
9850     33.8M
9851     49.0M
9852     34.3M
9853     75.7M
9854     92.2M
Name: ContractCost, Length: 9855, dtype: object

### Getting The Fastest and Longest Construction Period

In [19]:
# Convert CompletionDateActual into datetime
df['CompletionDateActual'] = pd.to_datetime(df['CompletionDateActual'])
df['StartDate'] = pd.to_datetime(df['StartDate'])

df['TotalDays'] = (df['CompletionDateActual'] - df['StartDate']).dt.days

#Get min and max
min_period = df['TotalDays'].min()
max_period = df['TotalDays'].max()

print("\nMinimum Construction Period (days):", min_period)
print("Maximum Construction Period (days):", max_period)

Minimum Construction Period (days): 14
Maximum Construction Period (days): 2012

In [20]:
# Fastest Construction Period
df[(df['TotalDays'] == 14)]

,InfraYear,Region,Province,Municipality,ProjectDescription,ContractCost,Contractor,CompletionDateActual,StartDate,ContractID,CompletionDate,TotalDays
4561,2021,Region IV-A,RIZAL,NaN,"Construction of Slope Protection at Creek, Sit...",4.8M,PEARLCAST CONSTRUCTION & TRADING,2022-09-19,2022-09-05,21DO0071,2023-01-31,14

In [21]:
# Longest Construction Period
df[(df['TotalDays'] == 2012)]

,InfraYear,Region,Province,Municipality,ProjectDescription,ContractCost,Contractor,CompletionDateActual,StartDate,ContractID,CompletionDate,TotalDays
1245,2018,Region III,BATAAN,NaN,"Almacen River Improvement Project, Hermosa and...",136.3M,"TOKWING CONSTRUCTION, CORP.(FOR; TOKWING CONS...",2023-08-31,2018-02-26,18C00035,2023-08-30,2012

### Getting the Infrastructure Year Of 'WAWAO BUILDERS'

In [22]:
df[df['Contractor'] == 'WAWAO BUILDERS']['InfraYear'].value_counts().sort_index()

InfraYear
2022     9
2023    27
2024    17
Name: count, dtype: int64

### Getting The Construction Period

In [23]:
# Function to compute months + days difference
def months_days_diff(start, end):
    if pd.isna(start) or pd.isna(end):
        return None
    rd = relativedelta(end, start)   # end - start
    return f"{abs(rd.years)*12 + rd.months} months {abs(rd.days)} days"

# Apply row by row
df['ConstructionPeriod'] = df.apply(
    lambda row: months_days_diff(row['StartDate'], row['CompletionDateActual']),
    axis=1
)


df['ConstructionPeriod']

0         3 months 8 days
1        4 months 26 days
2         5 months 1 days
3        2 months 20 days
4        5 months 27 days
              ...
9850     10 months 8 days
9851    11 months 25 days
9852     9 months 14 days
9853    16 months 11 days
9854     5 months 21 days
Name: ConstructionPeriod, Length: 9855, dtype: object